services:
  game-library:
    build: .
    container_name: game-library
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped
